Repository buildpacks/libcnb, pull requests merged in 2021-11, with the labels that each got.

#89 Renames poet -> log
  build.go
  detect.go
  log/init_test.go
  log/logger.go
  log/logger_test.go
Labels: type:enhancement, semver:major

#94 Updates libcnb to support buildpacks API 0.7
  build.go
  build_test.go
  detect.go
  detect_test.go
Labels: type:enhancement, semver:minor

#95 Adds a convenience method for getting the build, launch and layer BOM file paths
  application.go
  build.go
  layer.go
  layer_test.go
  platform.go
Labels: type:enhancement, semver:minor

#96 Adds a convenience method for getting the build, launch and layer BOM file paths
  application.go
  build.go
  build_test.go
  layer.go
  layer_test.go
Labels: type:enhancement, semver:major

#98 Polish PR: Additional updates for SBOM Support
  build.go
  build_test.go
  buildpack.go
  layer.go
  layer_test.go
Labels: type:enhancement, semver:patch

#97 Additional updates for SBOM Support
  build.go
  build_test.go
  buildpack.go
  layer.go
  layer_test.go
Labels: type:enhancement, semver:patch

#99 Fixes bug with Warning message regarding SBOM format
  build.go
  build_test.go
Labels: type:bug, semver:patch
