Repository buildpacks/libcnb, pull requests merged in 2022-05, with the labels that each got.

#139 Removes usage of ioutil
  build_test.go
  detect_test.go
  formatter_test.go
  internal/config_map.go
  internal/config_map_test.go
  internal/directory_contents_test.go
  internal/environment_writer.go
  internal/environment_writer_test.go
  internal/toml_writer_test.go
  layer_test.go
  main_test.go
  platform_test.go
Labels: type:enhancement, semver:patch

#142 Forward-port v1 changes to v2
  .github/pipeline-version
  .github/pipelines-version
  .github/workflows/synchronize-labels.yml
  .github/workflows/tests.yml
  .github/workflows/update-pipeline.yml
  build.go
  build_test.go
  buildpack_test.go
  detect.go
  detect_test.go
  go.mod
  go.sum
  process.go
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: type:enhancement, semver:patch

#141 Adds layer.Reset function
  layer.go
  layer_test.go
Labels: type:enhancement, semver:minor

#145 Removes TODOs around CNB_BUILDPACK_DIR
  build.go
  build_test.go
  detect.go
  detect_test.go
  layer_test.go
Labels: type:task, semver:patch

#147 Modifies bindings API to improve consistency
  build.go
  detect.go
  platform.go
  platform_test.go
Labels: type:enhancement, semver:major
