Repository buildpacks/libcnb, pull requests merged in 2022-04, with the labels that each got.

#133 Add support for working-directory in launch.toml (API>=0.8)
  application.go
  build.go
  build_test.go
Labels: type:enhancement, semver:minor

#134 Add semver checks
  build.go
  build_test.go
  go.mod
  go.sum
Labels: type:task, semver:patch

#124 Make a configurable Logger interface
  build.go
  build_test.go
  config.go
  detect.go
  detect_test.go
  log/init_test.go
  log/logger.go
  log/logger_test.go
  main.go
  main_test.go
  mocks/environment_writer.go
  mocks/exec_d.go
  mocks/exec_d_writer.go
  mocks/exit_handler.go
  mocks/logger.go
  mocks/toml_writer.go
Labels: type:enhancement, semver:major

#131 Add support for buildpack api 0.8
  build.go
  build_test.go
  detect.go
  detect_test.go
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: type:enhancement, semver:minor
