Repository buildpacks/libcnb, pull requests merged in 2022-08, with the labels that each got.

#167 Use curl to install richgo
  .github/pipeline-descriptor.yml
Labels: type:task, semver:patch

#166 Use curl to install richgo
  .github/pipeline-descriptor.yml
Labels: type:task, semver:patch

#168 Update pipelines
  .github/pipeline-version
  .github/pipelines-version
  .github/workflows/pb-minimal-labels.yml
  .github/workflows/pb-synchronize-labels.yml
  .github/workflows/pb-tests.yml
  .github/workflows/pb-update-draft-release.yml
  .github/workflows/pb-update-go.yml
  .github/workflows/pb-update-pipeline.yml
Labels: semver:minor, type:dependency-upgrade

#171 Bump pipeline from 1.23.0 to 1.25.2
  .github/workflows/pb-minimal-labels.yml
  .github/workflows/pb-synchronize-labels.yml
  .github/workflows/pb-tests.yml
  .github/workflows/pb-update-draft-release.yml
  .github/workflows/pb-update-go.yml
  .github/workflows/pb-update-pipeline.yml
Labels: type:task, semver:patch

#164 Provide example on using `libcnb.Detector` interface
  example_build_test.go
  example_detect_test.go
  go.mod
  go.sum
Labels: type:documentation, semver:patch
